// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/clavix-themes/BoldTypographic.tsx": () => import("../components/mockups/clavix-themes/BoldTypographic.tsx"),
  "./components/mockups/clavix-themes/CleanWhite.tsx": () => import("../components/mockups/clavix-themes/CleanWhite.tsx"),
  "./components/mockups/clavix-themes/LightWarm.tsx": () => import("../components/mockups/clavix-themes/LightWarm.tsx"),
  "./components/mockups/clavix-themes/ModernGradient.tsx": () => import("../components/mockups/clavix-themes/ModernGradient.tsx"),
  "./components/mockups/clavix-themes/NavyGold.tsx": () => import("../components/mockups/clavix-themes/NavyGold.tsx")
};
